TALC compatibility changes
CH-Earth/pbhmCourse_student pull request #28
Opened 2024-02-05 18:57 UTC by kasra-keshavarz

Necessary changes for the workflows/assignments of this course. Various commits describe the necessary changes, but in summary:
* A new list of modules need to be loaded every time users need to run the workflows in terminal,
* Necessary changes has been implemented in the relevant Jupyter Notebooks,
* Adding instruction for activating the Python environment for this course,
* Adding necessary instruction in the Jupyter Notebook,
* SUMMA has been re-compiled on TALC, so the relevant paths have been changes,
* The workflow to compile SUMMA is not part of this PR,
* New instructions will follow based on needs

2024-02-06 05:31 UTC, wknoben requested changes

2024-02-06 05:31 UTC, wknoben commented on 0_prerequisits/hpc-env/README.md
Minor, but `prerequisites` needs an extra `e`

2024-02-06 05:31 UTC, wknoben commented on 0_prerequisits/hpc-env/README.md
> +$ cp pbhm-mods $HOME/.module
Would be good to specify if students need to `cd` into a specific dir before executing this command:
```
cd $HOME/pbhmCourse_student/0_prerequisites/hpc-env
```

2024-02-06 05:31 UTC, wknoben commented on 0_prerequisits/hpc-env/README.md
> +$ cp pbhm-mods $HOME/.module
Changing this line to 
```
cp /work/TALC/enci619.05_2024w/local/modules/pbhm-mods $HOME/.module
```
Would maybe also fix this?

2024-02-06 05:31 UTC, wknoben commented on 0_prerequisits/hpc-env/README.md
affects copy command too

2024-02-06 05:31 UTC, wknoben commented on 0_prerequisits/jupyter/README.md
> +The Jupyter environment for the `TALC` cluster is located in the following: https://talc.ucalgary.ca:8000/hub/login. You can use your UC username and password to login.
Might be good to add a specific call out that in this case, user name does not mean email address. E.g., use only the part before the `@` in `someone@ucalgary.ca`.
I know the instructions already say user name (not email), but in almost every other SSO UCal uses email address is either needed or also works - this one seems an exception to that

2024-02-06 05:31 UTC, wknoben commented on 0_prerequisits/python-env/README.md
> +# Using the dedicated Python enviornment in terminal
I expect we can cover this in the assignment description, but might be good to specify that this takes place in the terminal after ssh'ing into TALC

2024-02-06 05:31 UTC, wknoben commented on 0_prerequisits/jupyter/README.md
> +# TALC Jupyter enviornment
I expect we can cover this in the assignment description, but might be good to specify that this takes place in a standard web browser, after the other steps have been completed

2024-02-06 05:31 UTC, wknoben commented on 0_prerequisits/hpc-env/README.md
> +# Saving list of modules for `TALC`
I expect we can cover this in the assignment description, but might be good to specify that this takes place in the terminal after ssh'ing into TALC

2024-02-06 05:31 UTC, wknoben commented on 0_prerequisits/python-env/README.md
> +> You need to select the appropriate Python environment as a Kernel to run Notebooks for Assignment #3. After installing the Python environment as a Kernel, you can find the Kernel name in Jupyter No
In my case it popped a warning/error when opening the first notebook. Might be good to mention that possibility as well

2024-02-06 05:31 UTC, wknoben commented on 3_process_based_modelling/1a_pysumma_functionality.ipynb
The plotting is incredibly slow (over VPN at least), but this completes as expected

2024-02-06 05:31 UTC, wknoben commented on 3_process_based_modelling/1b_pysumma_example.ipynb
Completes as expected

2024-02-06 05:31 UTC, wknoben commented on 3_process_based_modelling/2a_reynolds_mountain_east.ipynb
Completes as expected - tested with full answers to all exercises in this notebook

2024-02-06 05:31 UTC, wknoben commented on 3_process_based_modelling/2a_reynolds_mountain_east.ipynb
Would be good to clear all cell outputs before merging - this keeps the history smaller

2024-02-06 05:31 UTC, wknoben commented on 3_process_based_modelling/2b_plumber_sites.ipynb
Would be good to clear all cell outputs before merging

2024-02-06 05:31 UTC, wknoben commented on 3_process_based_modelling/2c_bow_river_above_banff.ipynb
This file needs updates to the SUMMA exe location and library locations

2024-02-06 05:31 UTC, wknoben commented on 3_process_based_modelling/2c_bow_river_above_banff.ipynb
Completes as expected - tested with downloading hydroshare resource and answers to all questions

2024-02-06 05:31 UTC, wknoben commented on 4_high_performance_computing/scripts/ex_2.1_merge_output.sh
libraries load as expected

2024-02-06 05:31 UTC, wknoben commented on 3_process_based_modelling/2b_plumber_sites.ipynb
Still running for the sake of it, but so far it seems to work

2024-02-06 15:22 UTC, kasra-keshavarz commented on 0_prerequisits/hpc-env/README.md
> +$ cp pbhm-mods $HOME/.module
So, the file is also available where this README.md file is located in this repository. But, I've changed it to the line you've mentioned here.

2024-02-06 15:32 UTC, kasra-keshavarz commented on 0_prerequisits/python-env/README.md
> +> You need to select the appropriate Python environment as a Kernel to run Notebooks for Assignment #3. After installing the Python environment as a Kernel, you can find the Kernel name in Jupyter No
What was the warning/error? This should not happen.

2024-02-06 15:33 UTC, kasra-keshavarz commented on 3_process_based_modelling/1a_pysumma_functionality.ipynb
Yeah, sorry about this. There isn't much we could do at our end.

2024-02-06 15:33 UTC, kasra-keshavarz commented on 3_process_based_modelling/1b_pysumma_example.ipynb
Great

2024-02-06 15:33 UTC, kasra-keshavarz commented on 3_process_based_modelling/2a_reynolds_mountain_east.ipynb
Fantastic

2024-02-06 15:36 UTC, kasra-keshavarz commented on 3_process_based_modelling/2c_bow_river_above_banff.ipynb
Done, thanks.

2024-02-06 15:36 UTC, kasra-keshavarz commented on 3_process_based_modelling/2c_bow_river_above_banff.ipynb
Perfect, thanks.

2024-02-06 15:37 UTC, kasra-keshavarz commented on 4_high_performance_computing/scripts/ex_2.1_merge_output.sh
Great

2024-02-06 15:37 UTC, kasra-keshavarz commented on 3_process_based_modelling/2b_plumber_sites.ipynb
Yep, I remember this taking a while to run. But, it ran on my end without any issues.

2024-02-06 16:34 UTC, kasra-keshavarz commented
I've tried to address your comments, let me know what you think.

2024-02-06 18:10 UTC, kasra-keshavarz commented on 0_prerequisits/python-env/README.md
> +> You need to select the appropriate Python environment as a Kernel to run Notebooks for Assignment #3. After installing the Python environment as a Kernel, you can find the Kernel name in Jupyter No
Make a note, so students don't freak out.

2024-02-06 20:55 UTC, kasra-keshavarz commented on 0_prerequisits/python-env/README.md
> +> You need to select the appropriate Python environment as a Kernel to run Notebooks for Assignment #3. After installing the Python environment as a Kernel, you can find the Kernel name in Jupyter No
Done as well.

2024-02-08 17:25 UTC, wknoben approved these changes
looks good to me

2024-02-08 17:25 UTC, merged